project:
  type: book
  output-dir: _book

book:
  title: "Tidy design principles"
  reader-mode: true

  page-footer:
    left: |
      Tidy design principles was written by Hadley Wickham
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://design.tidyverse.org
  repo-url: https://github.com/tidyverse/design
  repo-branch: main
  repo-actions: [edit, issue]
  
  chapters:
    - index.Rmd
    - unifying.Rmd
    
    - part: Implementation
      chapters:
      - names.Rmd
      - call-data-details.Rmd
      - function-names.Rmd
        
    - part: Scannable definitions
      chapters:
      - args-data-details.Rmd
      - args-hidden.Rmd
      - dots-position.Rmd
      - def-required.Rmd
      - args-independence.Rmd
      - def-enum.Rmd
      - def-short.Rmd
      - cs-setNames.Rmd
      - cs-stringr.Rmd
    
    - part: Function arguments
      chapters: 
      - cs-rep.Rmd
      - def-magical.Rmd
      - def-inform.Rmd
      - def-user.Rmd
      - cs-rgb.Rmd
      - dots-data.Rmd
      - dots-prefix.Rmd
      - dots-inspect.Rmd
      - cs-mapply-pmap.Rmd
    
    - part: Outputs
      chapters: 
      - out-multi.Rmd
      - out-type-stability.Rmd
      - out-vectorisation.Rmd
      - out-invisible.Rmd

    - part: Evolution
      chapters: 
      - changes-multivers.Rmd
    
    - part: Side effects
      chapters: 
      - side-effects.Rmd
      - spooky-action.Rmd

    - part: Errors
      chapters: 
      - err-call.Rmd
      - err-constructor.Rmd
    
    
  appendices:
    - glossary.Rmd

format:
  html:
    theme:
    - cosmo
    - r4ds.scss
    code-link: true

    author-meta: "Hadley Wickham"
    include-in-header: "plausible.html"
    callout-appearance: simple

editor: visual

